#!/bin/bash

# ~/.bashrc
# ~/.gitconfig
# ~/.inputrc
# ~/.minttyrc
# ~/.nanorc
# ~/.screenrc

for x in bashrc gitconfig nanorc ; do
    ln -fs "$(pwd)/.${x}" ~
done

# Screen configuration
if [ "$(uname -o)" == "GNU/Linux" ] ; then
    ln -fs "$(pwd)/.screenrc" ~
elif [ "$(uname -o)" == "Cygwin" ] ; then
    ln -fs "$(pwd)/.inputrc" ~/.inputrc
    ln -fs "$(pwd)/.minttyrc" ~/.minttyrc
    ln -fs "$(pwd)/.screenrc.cygwin" ~/.screenrc
fi
